import {
  IsEmail,
  IsNotEmpty,
  IsBoolean,
  IsOptional,
  IsString,
  IsArray,
  IsUUID,
  ArrayUnique,
  ArrayMaxSize,
  MaxLength,
  MinLength,
  Matches,
} from 'class-validator';
import { Transform } from 'class-transformer';

/**
 * DTO User Create.
 *
 * Note: `id` and `status` are generated by the server (auto-increment and default `false`, respectively).
 */
export class CreateUserDto {
  /**
   * User email. Normalized to lowercase and trimmed of leading/trailing spaces before storage.
   */
  @IsEmail({}, { message: 'El email debe tener un formato válido' })
  @IsNotEmpty({ message: 'El email es obligatorio' })
  @MaxLength(100, { message: 'El email no puede superar los 100 caracteres' })
  @Transform(({ value }: { value: unknown }) =>
    typeof value === 'string' ? value.trim().toLowerCase() : value,
  )
  email: string;

  /**
   * User name.
   */
  @IsString({ message: 'El nombre debe ser una cadena de texto' })
  @IsNotEmpty({ message: 'El nombre es obligatorio' })
  @MinLength(3, { message: 'El nombre debe tener al menos 3 caracteres' })
  @MaxLength(35, { message: 'El nombre no puede superar los 35 caracteres' })
  name: string;

  /**
   * Password in plain text. Stored hashed with bcrypt.
   * The 72-character limit matches bcrypt's internal limit.
   */
  @IsString({ message: 'La contraseña debe ser una cadena de texto' })
  @IsNotEmpty({ message: 'La contraseña es obligatoria' })
  @MinLength(8, { message: 'La contraseña debe tener al menos 8 caracteres' })
  @MaxLength(72, {
    message:
      'La contraseña no puede superar los 72 caracteres (límite de bcrypt)',
  })
  @Matches(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/, {
    message:
      'La contraseña debe contener al menos una minúscula, una mayúscula y un número',
  })
  password: string;

  /**
   * User status.
   */
  @IsBoolean({ message: 'El status debe ser un valor booleano' })
  @IsOptional()
  status: boolean;

  /**
   * Roles to assign to the user (optional).
   *
   * Each entry must be the UUID of an existing role. Roles are seeded at
   * application startup (admin, manager, sales) and can be listed through
   * `GET /users/roles`. If omitted, the user is created without roles.
   */
  @IsNotEmpty()
  @IsArray({ message: 'Los roles deben ser un arreglo' })
  @ArrayUnique({ message: 'Los roles no pueden repetirse' })
  @ArrayMaxSize(10, { message: 'No se pueden asignar más de 10 roles' })
  @IsUUID('4', { each: true, message: 'Cada rol debe ser un UUID válido' })
  roleIds?: string[];
}
